#!/bin/bash

GREP="grep --color=never"

usage()
{
    echo "$0: {local|remote} [REMOTE]" >&2
}

mode=$1
remote=$2

if [ -z $mode ]; then
    echo "$0: no mode specified" >&2
    usage
    exit 1
fi

if [ $mode != "remote" ] && [ $mode != "local" ]; then
    echo "$0: unknown mode: $mode" >&2
    usage
    exit 1
fi

if [ $mode == "remote" ] && [ -z $remote ]; then
    echo "$0: no remote specified" >&2
    usage
    exit 1
fi

if [ $mode == "local" ]; then
    branches=$(git branch --merged | $GREP -v master | $GREP -v '*')
    if [ -z $branches ]; then
        echo "$0: no merged local branches found"
        exit 0
    fi

    git branch -d $branches
elif [ $mode == "remote" ]; then
    branches=$(git branch -r --merged | $GREP $remote/ | \
               $GREP -v master | sed -e "s/$remote\///g")
    if [ -z $branches ]; then
        echo "$0: no merged remote branches found"
        exit 0
    fi

    git push $remote --delete
fi
